### PR TITLE
upgrade package_config contraints

### PR DESCRIPTION
**Pull request by keertip**
for #6 

@sethladd @lrhn

### CODE REVIEW

**Comment by sethladd** [comment]
lgtm assuming tests passed? is this tested on our bots or travis?

**Comment by keertip** [comment]
Looks like testing on travis is not setup. Ran the tests locally, against 1.14-dev.7.0, they pass. One test fails on 1.14-dev.6.0

`00:00 +0 -1: loading load package: URIs
  No static method 'resolvePackageUri' declared in class 'Isolate'.
  NoSuchMethodError: method not found: 'resolvePackageUri'`

Probably should have a version constraint on the sdk.

**Comment by keertip** [comment]
@lrhn , PTAL

**Comment by lrhn** [comment]
LGTM

**Pull request merged**
